export const emailPattern = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i;

export const usStates = [
  'New York',
  'Massachusetts',
  'New Jersey',
  'Connecticut',
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Mexico',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
];

export const policy_signatures = [
  'medication_history_signature',
  'informed_consent_signature',
  'practice_policies_signature',
  'privacy_policy_signature',
  'telehealth_consent_signature',
];

export const base64Strings = [
  'guardian_signature',
  'honesty_signature',
  ...policy_signatures,
];

export const initialValues = {
  first_name: '',
  last_name: '',
  date_of_birth: '',
  phone: '',
  email: '',
  for_minor_child: '',
  guardian_signature: '',
  relationship_with_child: '',
  sex_assigned_at_birth: '',
  gender: '',
  address_one: '',
  address_two: '',
  city: '',
  state: '',
  zip_code: '',
  reason_for_visit: '',
  mental_health_care_type: '',
  therapy_availability: '',
  suicidal_thoughts: '',
  hearing_impairment: '',
  interpreter_guidelines: '',
  emergency_contact_info: '',
  emergency_contact_phone: '',
  insurance_id: '',
  insurance_card_front: '',
  insurance_card_back: '',
  credit_card_number: '',
  credit_card_exp_date: '',
  credit_card_csv: '',
  billing_zip_code: '',
  policy_agreement: '',
  medication_history_signature: '',
  informed_consent_signature: '',
  practice_policies_signature: '',
  privacy_policy_signature: '',
  telehealth_consent_signature: '',

  // New fields
  seen_health_professional: '',
  symptoms_past_six_months: [],
  symptoms_other: '',
  current_medications: '',
  medication_allergies: '',
  alcohol_frequency: '',
  alcohol_quantity: '',
  drug_use: '',
  hospitalized_psych: '',
  hospitalized_psych_details: '',
  family_history_mental_illness: '',
  personal_medical_history: [],
  medical_other: '',
  height: '',
  weight: '',
  pregnant_or_breastfeeding: '',
  recent_physical_exam: '',
  physical_exam_details: '',
  relationship_details: '',
  education_level: '',
  current_occupation: '',
  living_situation: '',
  has_weapons: '',
  honesty: '',
  honesty_signature: '',
};
