import Signature from './signature';

const Terms = () => {
  return (
    <section className='mt-12'>
      {/* CONSENT FOR TELEHEALTH CONSULTATION */}
      <article>
        <h3 className='mb-4 font-medium'>
          CONSENT FOR TELEHEALTH CONSULTATION
        </h3>
        <ol className='mb-4 list-decimal ps-4'>
          <li>
            I understand that my health care provider wishes me to engage in a
            telehealth consultation.
          </li>
          <li>
            I understand that the video conferencing technology will not be the
            same as a direct client/health care provider visit due to the fact
            that I will not be in the same room as my provider.
          </li>
          <li>
            I understand that a telehealth consultation has potential benefits
            including easier access to care and the convenience of meeting from
            a location of my choosing.
          </li>
          <li>
            I understand there are potential risks to this technology, including
            interruptions, unauthorized access, and technical difficulties. I
            understand that my health care provider or I can discontinue the
            telehealth consult/visit if it is felt that the videoconferencing
            connections are not adequate
          </li>
        </ol>

        <p className='my-4'>
          BY SIGNING BELOW I CERTIFY THAT I HAVE READ, UNDERSTAND AND AGREE TO
          THE ITEMS CONTAINED IN THIS DOCUMENT.
        </p>

        <Signature />
      </article>

      {/* NOTICE OF PRIVACY PRACTICES */}
      <article>
        <p className='my-1'>This notice went into effect on November 1, 2021</p>

        <h3 className='mb-4 font-medium'>NOTICE OF PRIVACY PRACTICES</h3>

        <p>
          THIS NOTICE DESCRIBES HOW HEALTH INFORMATION MAY BE USED AND DISCLOSED
          AND HOW YOU CAN GET ACCESS TO THIS INFORMATION. PLEASE REVIEW IT
          CAREFULLY.
        </p>

        <ol className='list-[upper-roman] space-y-4 ps-4'>
          <li>
            OUR PLEDGE REGARDING HEALTH INFORMATION: Orenda Psychiatry
            understands that health information about you and your health care
            is personal. Orenda Psychiatry is committed to protecting health
            information about you. Orenda Psychiatry creates a record of the
            care and services you receive from us. We need this record to
            provide you with quality care and to comply with certain legal
            requirements. This notice applies to all of the records of your care
            generated by this mental health care practice. This notice will tell
            you about the ways in which we may use and disclose health
            information about you. We also describe your rights to the health
            information we keep about you, and describe certain obligations we
            have regarding the use and disclosure of your health information.
            Orenda Psychiatry is required by law to:
            <ul className='sublist-disc'>
              <li>
                Make sure that protected health information (“PHI”) that
                identifies you is kept private.
              </li>
              <li>
                Give you this notice of Orenda Psychiatry’s legal duties and
                privacy practices with respect to health information.
              </li>
              <li>
                Follow the terms of the notice that is currently in effect.
              </li>
              <li>
                Orenda Psychiatry can change the terms of this Notice, and such
                changes will apply to all information we have about you. The new
                Notice will be available upon request.
              </li>
            </ul>
          </li>

          <li className='space-y-4'>
            <p>
              HOW ORENDA PSYCHIATRY MAY USE AND DISCLOSE HEALTH INFORMATION
              ABOUT YOU: The following categories describe different ways that
              Orenda Psychiatry uses and disclose health information. Not every
              use or disclosure in a category will be listed. However, all of
              the ways we are permitted to use and disclose information will
              fall within one of the categories.
            </p>
            <p>
              For Treatment Payment, or Health Care Operations: Federal privacy
              rules (regulations) allow health care providers who have direct
              treatment relationship with the patient/client to use or disclose
              the patient/client’s personal health information without the
              patient’s written authorization, to carry out the health care
              provider’s own treatment, payment or health care operations.
              Orenda Psychiatry may also disclose your protected health
              information for the treatment activities of any health care
              provider. This too can be done without your written authorization.
              For example, if a clinician were to consult with another licensed
              health care provider about your condition, we would be permitted
              to use and disclose your personal health information, which is
              otherwise confidential, in order to assist the clinician in
              diagnosis and treatment of your mental health condition.
            </p>
            <p>
              Disclosures for treatment purposes are not limited to the minimum
              necessary standard because therapists and other health care
              providers need access to the full record and/or full and complete
              information in order to provide quality care. The word “treatment”
              includes, among other things, the coordination and management of
              health care providers with a third party, consultations between
              healthcare providers and referrals of a patient for health care
              from one health care provider to another.
            </p>
            <p>
              Lawsuits and Disputes: If you are involved in a lawsuit, Orenda
              Psychiatry may disclose health information in response to a court
              or administrative order. Orenda Psychiatry may also disclose
              health information about your child in response to a subpoena,
              discovery request, or other lawful process by someone else
              involved in the dispute, but only if efforts have been made to
              tell you about the request or to obtain an order protecting the
              information requested.
            </p>
          </li>

          <li>
            CERTAIN USES AND DISCLOSURES REQUIRE YOUR AUTHORIZATION:
            <ol className='sublist-decimal'>
              <li>
                Psychotherapy Notes. Orenda Psychiatry does keep “psychotherapy
                notes” as that term is defined in 45 CFR § 164.501, and any use
                or disclosure of such notes requires your Authorization unless
                the use or disclosure is:
                <ol
                  className='sublist-disc my-4 [list-style-type:lower-alpha]'
                  type='a'
                >
                  <li>For our use in treating you.</li>
                  <li>
                    For our use in training or supervising mental health
                    practitioners to help them improve their skills in group,
                    joint, family, or individual counseling or therapy.
                  </li>
                  <li>
                    For our use in defending myself in legal proceedings
                    instituted by you.
                  </li>
                  <li>
                    For use by the Secretary of Health and Human Services to
                    investigate our compliance with HIPAA.
                  </li>
                  <li>
                    Required by law and the use or disclosure is limited to the
                    requirements of such law.
                  </li>
                  <li>
                    Required by law for certain health oversight activities
                    pertaining to the originator of the psychotherapy notes.
                  </li>
                  <li>
                    Required by a coroner who is performing duties authorized by
                    law.
                  </li>
                  <li>
                    Required to help avert a serious threat to the health and
                    safety of others.
                  </li>
                </ol>
              </li>
              <li>
                Marketing Purposes. We will not use or disclose your PHI for
                marketing purposes.
              </li>
              <li>
                Sale of PHI. We will not sell your PHI in the regular course of
                our business.
              </li>
            </ol>
          </li>
          <li>
            CERTAIN USES AND DISCLOSURES DO NOT REQUIRE YOUR AUTHORIZATION.
            <br />
            Subject to certain limitations in the law, Orenda Psychiatry can use
            and disclose your PHI without your Authorization for the following
            reasons:
            <ol className='sublist-decimal'>
              <li>
                When disclosure is required by state or federal law, and the use
                or disclosure complies with and is limited to the relevant
                requirements of such law.
              </li>
              <li>
                For public health activities, including reporting suspected
                child, elder, or dependent adult abuse, or preventing or
                reducing a serious threat to anyone’s health or safety.
              </li>
              <li>
                For health oversight activities, including audits and
                investigations.
              </li>
              <li>
                For judicial and administrative proceedings, including
                responding to a court or administrative order, although my
                preference is to obtain an Authorization from you before doing
                so.
              </li>
              <li>
                For law enforcement purposes, including reporting crimes
                occurring on my premises.
              </li>
              <li>
                To coroners or medical examiners, when such individuals are
                performing duties authorized by law.
              </li>
              <li>
                For research purposes, including studying and comparing the
                mental health of patients who received one form of therapy
                versus those who received another form of therapy for the same
                condition.
              </li>
              <li>
                Specialized government functions, including, ensuring the proper
                execution of military missions; protecting the President of the
                United States; conducting intelligence or counter-intelligence
                operations; or, helping to ensure the safety of those working
                within or housed in correctional institutions.
              </li>
              <li>
                For workers’ compensation purposes. Although our preference is
                to obtain an Authorization from you, we may provide your PHI in
                order to comply with workers’ compensation laws.
              </li>
              <li>
                Appointment reminders and health related benefits or services.
                We may use and disclose your PHI to contact you to remind you
                that you have an appointment with us. We may also use and
                disclose your PHI to tell you about treatment alternatives, or
                other health care services or benefits that we offer.
              </li>
            </ol>
          </li>
          <li>
            CERTAIN USES AND DISCLOSURES REQUIRE YOU TO HAVE THE OPPORTUNITY TO
            OBJECT.
            <ol className='sublist-decimal'>
              <li>
                Disclosures to family, friends, or others. Orenda Psychiatry may
                provide your PHI to a family member, friend, or other person
                that you indicate is involved in your care or the payment for
                your health care, unless you object in whole or in part. The
                opportunity to consent may be obtained retroactively in
                emergency situations.
              </li>
            </ol>
          </li>

          <li>
            YOU HAVE THE FOLLOWING RIGHTS WITH RESPECT TO YOUR PHI:
            <ol className='sublist-decimal'>
              <li>
                The Right to Request Limits on Uses and Disclosures of Your PHI.
                You have the right to ask us not to use or disclose certain PHI
                for treatment, payment, or health care operations purposes. We
                are not required to agree to your request, and we may say “no”
                if we believe it would affect your health care.
              </li>
              <li>
                The Right to Request Restrictions for Out-of-Pocket Expenses
                Paid for In Full. You have the right to request restrictions on
                disclosures of your PHI to health plans for payment or health
                care operations purposes if the PHI pertains solely to a health
                care item or a health care service that you have paid for
                out-of-pocket in full.
              </li>
              <li>
                The Right to Choose How Orenda Psychiatry Sends PHI to You. You
                have the right to ask us to contact you in a specific way (for
                example, home or office phone) or to send mail to a different
                address, and we will agree to all reasonable requests.
              </li>
              <li>
                The Right to See and Get Copies of Your PHI. Other than
                “psychotherapy notes,” you have the right to get an electronic
                or paper copy of your medical record and other information that
                we have about you. We will provide you with a copy of your
                record, or a summary of it, if you agree to receive a summary,
                within 30 days of receiving your written request, and we may
                charge a reasonable, cost based fee for doing so.
              </li>
              <li>
                The Right to Get a List of the Disclosures We Have Made. You
                have the right to request a list of instances in which Orenda
                Psychiatry has disclosed your PHI for purposes other than
                treatment, payment, or health care operations, or for which you
                provided us with an Authorization. We will respond to your
                request for an accounting of disclosures within 60 days of
                receiving your request. The list we will give you will include
                disclosures made in the last six years unless you request a
                shorter time. We will provide the list to you at no charge, but
                if you make more than one request in the same year, we will
                charge you a reasonable cost based fee for each additional
                request.
              </li>
              <li>
                The Right to Correct or Update Your PHI. If you believe that
                there is a mistake in your PHI, or that a piece of important
                information is missing from your PHI, you have the right to
                request that we correct the existing information or add the
                missing information. We may say “no” to your request, but we
                will tell you why in writing within 60 days of receiving your
                request.
              </li>
              <li>
                The Right to Get a Paper or Electronic Copy of this Notice. You
                have the right get a paper copy of this Notice, and you have the
                right to get a copy of this notice by e-mail. And, even if you
                have agreed to receive this Notice via e-mail, you also have the
                right to request a paper copy of it.
              </li>
            </ol>
          </li>
        </ol>

        <p className='mb-4'>Acknowledgement of Receipt of Privacy Notice</p>
        <p className='mb-4'>
          Under the Health Insurance Portability and Accountability Act of 1996
          (HIPAA), you have certain rights regarding the use and disclosure of
          your protected health information. By checking the box below, you are
          acknowledging that you have received a copy of HIPAA Notice of Privacy
          Practices.
        </p>
        <p className='mb-4'>
          BY SIGNING BELOW I AM CERTIFY THAT I HAVE READ, UNDERSTAND AND AGREE
          TO THE PROVISION OF PSYCHIATRIC SERVICES BY ORENDA PSYCHIATRY AND ITS
          PROVIDERS.
        </p>

        <Signature />
      </article>
    </section>
  );
};
export default Terms;
